import { audiogramSVG, classifyLoss, pureToneAverage } from "./audiogram.js";

function escapeHTML(value) {
  return String(value ?? "")
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}

function display(value, fallback = "Not provided") {
  const text = String(value ?? "").trim();
  return text || fallback;
}

/**
 * Summarise one ear for a printable report.
 *
 * @param {{air?:Array<{freq:number,level:number}>}} ear
 * @returns {{pta:number|null, classification:string, measuredFrequencies:number}}
 */
export function summariseEar(ear = {}) {
  const pta = pureToneAverage(ear);
  return {
    pta,
    classification: classifyLoss(pta),
    measuredFrequencies: Array.isArray(ear.air) ? ear.air.length : 0,
  };
}

/**
 * Create a self-contained, printable clinic report.
 *
 * @param {object} data Audiogram data.
 * @param {{patientName?:string, patientId?:string, date?:string, clinician?:string, clinic?:string, notes?:string, title?:string}} [meta]
 * @returns {string} Complete HTML document.
 */
export function reportHTML(data = {}, meta = {}) {
  const right = summariseEar(data.right);
  const left = summariseEar(data.left);
  const date = display(meta.date, new Date().toISOString().slice(0, 10));
  const title = display(meta.title, "Hearing screening report");
  const svg = audiogramSVG(data, {
    width: 760,
    height: 550,
    title: "Pure-tone screening audiogram",
  });
  const pta = (summary) =>
    summary.pta === null ? "Incomplete" : `${summary.pta.toFixed(1)} dB HL`;

  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>${escapeHTML(title)}</title>
  <style>
    :root{font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#17333a;background:#edf5f4}
    *{box-sizing:border-box}
    body{margin:0;padding:32px}
    main{max-width:960px;margin:auto;background:#fff;padding:42px;border-radius:18px;box-shadow:0 16px 48px rgba(21,63,68,.12)}
    header{display:flex;justify-content:space-between;gap:24px;align-items:flex-start;border-bottom:3px solid #0f8d82;padding-bottom:20px}
    h1{font-size:28px;margin:0 0 5px;color:#0a5a63}
    h2{font-size:16px;margin:0 0 14px;color:#31555c;text-transform:uppercase;letter-spacing:.08em}
    p{line-height:1.55}
    .muted{color:#60757b;font-size:13px}
    .meta{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:13px 28px;margin:28px 0}
    .field{border-bottom:1px solid #cbd9d9;padding-bottom:8px}
    .label{display:block;color:#667d82;font-size:11px;text-transform:uppercase;letter-spacing:.08em;margin-bottom:4px}
    .value{font-weight:650}
    .summary{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin:22px 0}
    .ear{border:1px solid #cbdcdb;border-radius:12px;padding:18px;background:#f8fbfa}
    .ear.right{border-top:4px solid #d62f3f}.ear.left{border-top:4px solid #1769aa}
    .ear strong{font-size:20px}.ear span{display:block;color:#5d7479;margin-top:5px}
    .chart{margin:16px 0}.chart svg{width:100%;height:auto}
    .notes{min-height:58px;white-space:pre-wrap;border:1px solid #d7e2e1;border-radius:9px;padding:12px}
    .disclaimer{margin-top:24px;padding:14px 16px;background:#f2f7f6;border-left:4px solid #0f8d82;font-size:12px;color:#50696f}
    button{position:fixed;right:24px;top:24px;border:0;border-radius:999px;background:#0b776f;color:#fff;padding:12px 20px;font:inherit;font-weight:700;cursor:pointer;box-shadow:0 8px 24px rgba(9,94,89,.24)}
    @media(max-width:680px){body{padding:0}main{padding:24px;border-radius:0}.meta,.summary{grid-template-columns:1fr}button{position:static;margin:0 0 20px}}
    @media print{@page{size:A4;margin:12mm}body{padding:0;background:#fff}main{padding:0;box-shadow:none;max-width:none}button{display:none}.chart{break-inside:avoid}.disclaimer{break-inside:avoid}}
  </style>
</head>
<body>
  <button type="button" onclick="window.print()">Print report</button>
  <main>
    <header>
      <div><h1>${escapeHTML(title)}</h1><div class="muted">Generated by OpenAudiogram</div></div>
      <div><span class="label">Report date</span><span class="value">${escapeHTML(date)}</span></div>
    </header>
    <section class="meta" aria-label="Patient and clinic details">
      <div class="field"><span class="label">Patient</span><span class="value">${escapeHTML(display(meta.patientName))}</span></div>
      <div class="field"><span class="label">Patient ID</span><span class="value">${escapeHTML(display(meta.patientId))}</span></div>
      <div class="field"><span class="label">Clinic</span><span class="value">${escapeHTML(display(meta.clinic))}</span></div>
      <div class="field"><span class="label">Clinician</span><span class="value">${escapeHTML(display(meta.clinician))}</span></div>
    </section>
    <h2>Pure-tone average</h2>
    <section class="summary">
      <div class="ear right"><span class="label">Right ear</span><strong>${pta(right)}</strong><span>${escapeHTML(right.classification)}</span></div>
      <div class="ear left"><span class="label">Left ear</span><strong>${pta(left)}</strong><span>${escapeHTML(left.classification)}</span></div>
    </section>
    <section class="chart">${svg}</section>
    <h2>Notes</h2>
    <div class="notes">${escapeHTML(display(meta.notes, "No notes."))}</div>
    <p class="disclaimer"><strong>Screening notice:</strong> This report documents a hearing screening. Browser audio output requires device-specific calibration and is not a substitute for a diagnostic audiological evaluation. Refer results and clinical concerns to a qualified hearing professional.</p>
  </main>
</body>
</html>`;
}

/**
 * Open a generated report in a new browser tab.
 *
 * @param {object} data Audiogram data.
 * @param {object} [meta] Report metadata.
 * @returns {Window} Opened browser window.
 */
export function openReport(data, meta) {
  if (typeof window === "undefined") {
    throw new Error("openReport() requires a browser window.");
  }
  const reportWindow = window.open("", "_blank");
  if (!reportWindow) {
    throw new Error("The report window was blocked by the browser.");
  }
  reportWindow.document.open();
  reportWindow.document.write(reportHTML(data, meta));
  reportWindow.document.close();
  return reportWindow;
}
